import { MigrationInterface, QueryRunner } from "typeorm";

export class EntidadesCorregidas1768765992000 implements MigrationInterface {
    name = 'EntidadesCorregidas1768765992000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."docentes_nivelasignado_enum" AS ENUM('BASICA', 'BACHILLERATO', 'GLOBAL')`);
        await queryRunner.query(`CREATE TABLE "docentes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombres" character varying NOT NULL, "apellidos" character varying NOT NULL, "cedula" character varying, "telefono" character varying, "nivelAsignado" "public"."docentes_nivelasignado_enum" NOT NULL, "foto_perfil_url" character varying, "foto_titulo_url" character varying, "perfil_completo" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "usuario_id" uuid, CONSTRAINT "UQ_ceec48bf3028f7d71d736695029" UNIQUE ("cedula"), CONSTRAINT "REL_9fd711f473f0f2bf472de15268" UNIQUE ("usuario_id"), CONSTRAINT "PK_5e3b015bd4d79caf4eadbf340a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."usuarios_rol_enum" AS ENUM('ADMIN', 'DOCENTE', 'SECRETARIA')`);
        await queryRunner.query(`CREATE TYPE "public"."usuarios_estado_enum" AS ENUM('ACTIVO', 'INACTIVO', 'PENDIENTE')`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "rol" "public"."usuarios_rol_enum" NOT NULL DEFAULT 'DOCENTE', "estado" "public"."usuarios_estado_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_446adfc18b35418aac32ae0b7b5" UNIQUE ("email"), CONSTRAINT "PK_d7281c63c176e152e4c531594a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."tipos_evaluacion_nombre_enum" AS ENUM('INSUMOS', 'PROYECTO', 'EXAMEN')`);
        await queryRunner.query(`CREATE TABLE "tipos_evaluacion" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "periodo_lectivo_id" uuid NOT NULL, "nombre" "public"."tipos_evaluacion_nombre_enum" NOT NULL, "porcentaje" numeric(5,2) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d3afdae6c5387ea16014ab68be2" UNIQUE ("periodo_lectivo_id", "nombre"), CONSTRAINT "PK_6fbc365dba404918d499603ccdb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."periodos_lectivos_estado_enum" AS ENUM('ACTIVO', 'FINALIZADO')`);
        await queryRunner.query(`CREATE TABLE "periodos_lectivos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying NOT NULL, "fechaInicio" date NOT NULL, "fechaFin" date NOT NULL, "estado" "public"."periodos_lectivos_estado_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5422d93ecdf01f43c4b98634e02" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."trimestres_nombre_enum" AS ENUM('PRIMER TRIMESTRE', 'SEGUNDO TRIMESTRE', 'TERCER TRIMESTRE')`);
        await queryRunner.query(`CREATE TYPE "public"."trimestres_estado_enum" AS ENUM('ACTIVO', 'FINALIZADO', 'PENDIENTE')`);
        await queryRunner.query(`CREATE TABLE "trimestres" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" "public"."trimestres_nombre_enum" NOT NULL, "fechaInicio" date NOT NULL, "fechaFin" date NOT NULL, "estado" "public"."trimestres_estado_enum" NOT NULL DEFAULT 'PENDIENTE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "periodo_lectivo_id" uuid NOT NULL, CONSTRAINT "PK_2dfcbdf13495ca2a68c842548cf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cursos_nivel_enum" AS ENUM('OCTAVO', 'NOVENO', 'DECIMO', 'PRIMERO BACHILLERATO', 'SEGUNDO BACHILLERATO', 'TERCERO BACHILLERATO')`);
        await queryRunner.query(`CREATE TYPE "public"."cursos_especialidad_enum" AS ENUM('BASICA', 'TECNICO', 'CIENCIAS')`);
        await queryRunner.query(`CREATE TYPE "public"."cursos_estado_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "cursos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nivel" "public"."cursos_nivel_enum" NOT NULL, "paralelo" character varying NOT NULL, "especialidad" "public"."cursos_especialidad_enum" NOT NULL, "estado" "public"."cursos_estado_enum" NOT NULL DEFAULT 'ACTIVO', "periodo_lectivo_id" uuid NOT NULL, "docente_id" uuid, "estudiantes_matriculados" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_391c5a635ef6b4bd0a46cb75653" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."matriculas_origen_enum" AS ENUM('DISTRITO', 'MANUAL')`);
        await queryRunner.query(`CREATE TYPE "public"."matriculas_estado_enum" AS ENUM('ACTIVO', 'FINALIZADO', 'RETIRADO', 'ANULADO')`);
        await queryRunner.query(`CREATE TABLE "matriculas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "numero_de_matricula" character varying NOT NULL, "estudiante_id" uuid NOT NULL, "curso_id" uuid NOT NULL, "periodo_lectivo_id" uuid NOT NULL, "fecha_retiro" date, "origen" "public"."matriculas_origen_enum" NOT NULL DEFAULT 'DISTRITO', "archivo_origen" character varying, "observaciones" text, "estado" "public"."matriculas_estado_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3ebffa4c1e3360ba4b57cc881bf" UNIQUE ("numero_de_matricula"), CONSTRAINT "PK_4426123ba70495e947e719693b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."estudiantes_estado_enum" AS ENUM('ACTIVO', 'SIN_MATRICULA', 'GRADUADO', 'RETIRADO', 'INACTIVO_TEMPORAL')`);
        await queryRunner.query(`CREATE TABLE "estudiantes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombres_completos" character varying NOT NULL, "estudiante_cedula" character varying NOT NULL, "estudiante_email" character varying, "fecha_de_nacimiento" date, "direccion" character varying, "padre_nombre" character varying, "padre_apellido" character varying, "padre_cedula" character varying, "madre_nombre" character varying, "madre_apellido" character varying, "madre_cedula" character varying, "viven_juntos" boolean NOT NULL DEFAULT false, "representante_nombre" character varying, "representante_apellido" character varying, "representante_telefono" character varying, "representante_telefono_auxiliar" character varying, "representante_correo" character varying, "representante_parentesco" character varying, "datos_completos" boolean NOT NULL DEFAULT false, "estado" "public"."estudiantes_estado_enum" NOT NULL DEFAULT 'ACTIVO', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_be6edc873795eae3b8a8e772e8c" UNIQUE ("estudiante_cedula"), CONSTRAINT "UQ_a80207db4b5108109fee24010b8" UNIQUE ("estudiante_email"), CONSTRAINT "PK_34e9c0289e8e3f437ec6c902f6b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."materias_niveleducativo_enum" AS ENUM('BASICA', 'BACHILLERATO', 'GENERAL')`);
        await queryRunner.query(`CREATE TYPE "public"."materias_tipocalificacion_enum" AS ENUM('CUALITATIVA', 'CUANTITATIVA')`);
        await queryRunner.query(`CREATE TYPE "public"."materias_estado_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "materias" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying NOT NULL, "nivelEducativo" "public"."materias_niveleducativo_enum" NOT NULL, "tipoCalificacion" "public"."materias_tipocalificacion_enum" NOT NULL, "estado" "public"."materias_estado_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3715a51974d6fcefbc528059df6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."materias_curso_estado_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "materias_curso" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "materia_id" uuid NOT NULL, "curso_id" uuid NOT NULL, "docente_id" uuid, "periodo_lectivo_id" uuid NOT NULL, "estado" "public"."materias_curso_estado_enum" NOT NULL DEFAULT 'ACTIVO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e5027e028699f0ec81483fffeb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."promedio_trimestre_cualitativa_enum" AS ENUM('DA', 'AA', 'PA', 'NA')`);
        await queryRunner.query(`CREATE TABLE "promedio_trimestre" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "estudiante_id" uuid NOT NULL, "materia_curso_id" uuid NOT NULL, "trimestre_id" uuid NOT NULL, "promedio_insumos" numeric(4,2), "ponderado_insumos" numeric(4,2), "nota_proyecto" numeric(4,2), "ponderado_proyecto" numeric(4,2), "nota_examen" numeric(4,2), "ponderado_examen" numeric(4,2), "nota_final_trimestre" numeric(4,2) NOT NULL, "cualitativa" "public"."promedio_trimestre_cualitativa_enum" NOT NULL, "observaciones" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_bd9874fe7fc2fa339acc148dd27" UNIQUE ("estudiante_id", "materia_curso_id", "trimestre_id"), CONSTRAINT "PK_eff483208f1e1fc41db6de4fe6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."promedio_periodo_cualitativa_anual_enum" AS ENUM('DA', 'AA', 'PA', 'NA')`);
        await queryRunner.query(`CREATE TYPE "public"."promedio_periodo_cualitativa_final_enum" AS ENUM('DA', 'AA', 'PA', 'NA')`);
        await queryRunner.query(`CREATE TYPE "public"."promedio_periodo_estado_enum" AS ENUM('APROBADO', 'REPROBADO', 'SUPLETORIO')`);
        await queryRunner.query(`CREATE TABLE "promedio_periodo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "estudiante_id" uuid NOT NULL, "materia_curso_id" uuid NOT NULL, "periodo_lectivo_id" uuid NOT NULL, "nota_trimestre_1" numeric(4,2) NOT NULL, "nota_trimestre_2" numeric(4,2) NOT NULL, "nota_trimestre_3" numeric(4,2) NOT NULL, "promedio_anual" numeric(4,2) NOT NULL, "cualitativa_anual" "public"."promedio_periodo_cualitativa_anual_enum" NOT NULL, "nota_supletorio" numeric(4,2), "promedio_final" numeric(4,2), "cualitativa_final" "public"."promedio_periodo_cualitativa_final_enum", "estado" "public"."promedio_periodo_estado_enum" NOT NULL, "observaciones" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_91c7b963dddb920959d4004bf62" UNIQUE ("estudiante_id", "materia_curso_id", "periodo_lectivo_id"), CONSTRAINT "PK_377da5d926ea5545f81e24da438" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."insumos_estado_enum" AS ENUM('ACTIVO', 'BORRADOR', 'PUBLICADO', 'CERRADO')`);
        await queryRunner.query(`CREATE TABLE "insumos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "materia_curso_id" uuid NOT NULL, "trimestre_id" uuid NOT NULL, "docente_id" uuid NOT NULL, "nombre" character varying NOT NULL, "estado" "public"."insumos_estado_enum" NOT NULL DEFAULT 'BORRADOR', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b4e1b727a7b140e698e3a3dc7af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "recuperacion_insumo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "calificacion_insumo_id" uuid NOT NULL, "nota_recuperacion" numeric(4,2) NOT NULL, "intento" integer NOT NULL, "observaciones" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0dfdf35fe1bbe5764d45bcce374" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "calificacion_insumo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "insumo_id" uuid NOT NULL, "estudiante_id" uuid NOT NULL, "docente_id" uuid NOT NULL, "nota_original" numeric(4,2) NOT NULL, "nota_final" numeric(4,2), "observaciones" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_98550a940b73f450c02517796ce" UNIQUE ("insumo_id", "estudiante_id"), CONSTRAINT "PK_27cac9d96cc1a4a17c7d0572823" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "calificacion_proyecto" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "estudiante_id" uuid NOT NULL, "curso_id" uuid NOT NULL, "trimestre_id" uuid NOT NULL, "docente_id" uuid NOT NULL, "calificacion_proyecto" numeric(4,2) NOT NULL, "observaciones" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_76488cbe4ba95d513a6cf2706ce" UNIQUE ("estudiante_id", "curso_id", "trimestre_id"), CONSTRAINT "PK_4ef5482d2518df91207b03699ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "calificacion_examen" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "estudiante_id" uuid NOT NULL, "materia_curso_id" uuid NOT NULL, "trimestre_id" uuid NOT NULL, "docente_id" uuid NOT NULL, "calificacion_examen" numeric(4,2) NOT NULL, "observaciones" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f0286c63471b540536206518a14" UNIQUE ("estudiante_id", "materia_curso_id", "trimestre_id"), CONSTRAINT "PK_7edf4d9393eb7aa2ba089a8d8be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."calificacion_componente_cualitativo_calificacion_enum" AS ENUM('+A', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D')`);
        await queryRunner.query(`CREATE TABLE "calificacion_componente_cualitativo" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "estudiante_id" uuid NOT NULL, "curso_id" uuid NOT NULL, "materia_id" uuid NOT NULL, "trimestre_id" uuid NOT NULL, "calificacion" "public"."calificacion_componente_cualitativo_calificacion_enum", "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_49ab0cd27725307faedaba62199" UNIQUE ("estudiante_id", "curso_id", "materia_id", "trimestre_id"), CONSTRAINT "PK_f5b2e795ea5fafdbe542a17ba40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "docentes" ADD CONSTRAINT "FK_9fd711f473f0f2bf472de152688" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tipos_evaluacion" ADD CONSTRAINT "FK_36bab68eb442843210f999f0bff" FOREIGN KEY ("periodo_lectivo_id") REFERENCES "periodos_lectivos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trimestres" ADD CONSTRAINT "FK_f78557fe53353dc34626b3a2ea5" FOREIGN KEY ("periodo_lectivo_id") REFERENCES "periodos_lectivos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cursos" ADD CONSTRAINT "FK_2462e222e2e234709464df31bc6" FOREIGN KEY ("periodo_lectivo_id") REFERENCES "periodos_lectivos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cursos" ADD CONSTRAINT "FK_8c39b6011fb5a0da2a7c8f1b5dd" FOREIGN KEY ("docente_id") REFERENCES "docentes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matriculas" ADD CONSTRAINT "FK_12610cedecedccac6383361b8c0" FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matriculas" ADD CONSTRAINT "FK_de4dc94e001d9d72471c4937c50" FOREIGN KEY ("curso_id") REFERENCES "cursos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matriculas" ADD CONSTRAINT "FK_bd71f878d96006eeead7b7f5d80" FOREIGN KEY ("periodo_lectivo_id") REFERENCES "periodos_lectivos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materias_curso" ADD CONSTRAINT "FK_c8f507cef7e765cc533a23198c7" FOREIGN KEY ("materia_id") REFERENCES "materias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materias_curso" ADD CONSTRAINT "FK_84877e0a4ff0be4b67f1b16274c" FOREIGN KEY ("curso_id") REFERENCES "cursos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materias_curso" ADD CONSTRAINT "FK_feff830e9610edbe55a9b6b3b32" FOREIGN KEY ("docente_id") REFERENCES "docentes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "materias_curso" ADD CONSTRAINT "FK_bf8b5544d0448fbf0a8bb31628d" FOREIGN KEY ("periodo_lectivo_id") REFERENCES "periodos_lectivos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promedio_trimestre" ADD CONSTRAINT "FK_bf47d4453423f18490cc7d6292a" FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promedio_trimestre" ADD CONSTRAINT "FK_e47cd9f104abba623ebb012f9a3" FOREIGN KEY ("materia_curso_id") REFERENCES "materias_curso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promedio_trimestre" ADD CONSTRAINT "FK_b0dff7d0f98f1dbcd69709302c3" FOREIGN KEY ("trimestre_id") REFERENCES "trimestres"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promedio_periodo" ADD CONSTRAINT "FK_8da8000ef0d76c72fab20b817aa" FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promedio_periodo" ADD CONSTRAINT "FK_f06c421ba51cb55d57d56c23e03" FOREIGN KEY ("materia_curso_id") REFERENCES "materias_curso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promedio_periodo" ADD CONSTRAINT "FK_c3f62a6aba1c6a8466f35a89ff2" FOREIGN KEY ("periodo_lectivo_id") REFERENCES "periodos_lectivos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD CONSTRAINT "FK_0922d53d1d89e1c0fc7f5a32520" FOREIGN KEY ("materia_curso_id") REFERENCES "materias_curso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD CONSTRAINT "FK_ca616f37420a05cfee3d6bf0c62" FOREIGN KEY ("trimestre_id") REFERENCES "trimestres"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insumos" ADD CONSTRAINT "FK_e18815d1c9e73f0931bc3dbb7c0" FOREIGN KEY ("docente_id") REFERENCES "docentes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recuperacion_insumo" ADD CONSTRAINT "FK_6184280c96b9103f5b7fe977c71" FOREIGN KEY ("calificacion_insumo_id") REFERENCES "calificacion_insumo"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_insumo" ADD CONSTRAINT "FK_6171790fd84c31c450bd9c18272" FOREIGN KEY ("insumo_id") REFERENCES "insumos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_insumo" ADD CONSTRAINT "FK_a535e472ba9fe38f564f3928f8d" FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_insumo" ADD CONSTRAINT "FK_832d52f11722382c2fbc4b6a476" FOREIGN KEY ("docente_id") REFERENCES "docentes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_proyecto" ADD CONSTRAINT "FK_df26c8e636fa84a3087f50d3999" FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_proyecto" ADD CONSTRAINT "FK_ffe8982ab9cf876b70ada89df5a" FOREIGN KEY ("trimestre_id") REFERENCES "trimestres"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_proyecto" ADD CONSTRAINT "FK_d4057102e27776626e15bf247a4" FOREIGN KEY ("curso_id") REFERENCES "cursos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_proyecto" ADD CONSTRAINT "FK_80c684eb6db016f13d80a870941" FOREIGN KEY ("docente_id") REFERENCES "docentes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_examen" ADD CONSTRAINT "FK_fc0abd6e168d3d9fdae6899f877" FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_examen" ADD CONSTRAINT "FK_98564ccb80dfd8e8895925c63b7" FOREIGN KEY ("materia_curso_id") REFERENCES "materias_curso"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_examen" ADD CONSTRAINT "FK_3b25f7eee38602d3d14e38a271e" FOREIGN KEY ("trimestre_id") REFERENCES "trimestres"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_examen" ADD CONSTRAINT "FK_aa22bab586cea93e144a2ea877b" FOREIGN KEY ("docente_id") REFERENCES "docentes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_componente_cualitativo" ADD CONSTRAINT "FK_4308f4f4735a6ca047705270083" FOREIGN KEY ("estudiante_id") REFERENCES "estudiantes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_componente_cualitativo" ADD CONSTRAINT "FK_41084292aa99431506f4c48013d" FOREIGN KEY ("curso_id") REFERENCES "cursos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_componente_cualitativo" ADD CONSTRAINT "FK_ece44ba6714b59cf9f12295d8f6" FOREIGN KEY ("materia_id") REFERENCES "materias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "calificacion_componente_cualitativo" ADD CONSTRAINT "FK_04354476cd5ae19c0e697373757" FOREIGN KEY ("trimestre_id") REFERENCES "trimestres"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "calificacion_componente_cualitativo" DROP CONSTRAINT "FK_04354476cd5ae19c0e697373757"`);
        await queryRunner.query(`ALTER TABLE "calificacion_componente_cualitativo" DROP CONSTRAINT "FK_ece44ba6714b59cf9f12295d8f6"`);
        await queryRunner.query(`ALTER TABLE "calificacion_componente_cualitativo" DROP CONSTRAINT "FK_41084292aa99431506f4c48013d"`);
        await queryRunner.query(`ALTER TABLE "calificacion_componente_cualitativo" DROP CONSTRAINT "FK_4308f4f4735a6ca047705270083"`);
        await queryRunner.query(`ALTER TABLE "calificacion_examen" DROP CONSTRAINT "FK_aa22bab586cea93e144a2ea877b"`);
        await queryRunner.query(`ALTER TABLE "calificacion_examen" DROP CONSTRAINT "FK_3b25f7eee38602d3d14e38a271e"`);
        await queryRunner.query(`ALTER TABLE "calificacion_examen" DROP CONSTRAINT "FK_98564ccb80dfd8e8895925c63b7"`);
        await queryRunner.query(`ALTER TABLE "calificacion_examen" DROP CONSTRAINT "FK_fc0abd6e168d3d9fdae6899f877"`);
        await queryRunner.query(`ALTER TABLE "calificacion_proyecto" DROP CONSTRAINT "FK_80c684eb6db016f13d80a870941"`);
        await queryRunner.query(`ALTER TABLE "calificacion_proyecto" DROP CONSTRAINT "FK_d4057102e27776626e15bf247a4"`);
        await queryRunner.query(`ALTER TABLE "calificacion_proyecto" DROP CONSTRAINT "FK_ffe8982ab9cf876b70ada89df5a"`);
        await queryRunner.query(`ALTER TABLE "calificacion_proyecto" DROP CONSTRAINT "FK_df26c8e636fa84a3087f50d3999"`);
        await queryRunner.query(`ALTER TABLE "calificacion_insumo" DROP CONSTRAINT "FK_832d52f11722382c2fbc4b6a476"`);
        await queryRunner.query(`ALTER TABLE "calificacion_insumo" DROP CONSTRAINT "FK_a535e472ba9fe38f564f3928f8d"`);
        await queryRunner.query(`ALTER TABLE "calificacion_insumo" DROP CONSTRAINT "FK_6171790fd84c31c450bd9c18272"`);
        await queryRunner.query(`ALTER TABLE "recuperacion_insumo" DROP CONSTRAINT "FK_6184280c96b9103f5b7fe977c71"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP CONSTRAINT "FK_e18815d1c9e73f0931bc3dbb7c0"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP CONSTRAINT "FK_ca616f37420a05cfee3d6bf0c62"`);
        await queryRunner.query(`ALTER TABLE "insumos" DROP CONSTRAINT "FK_0922d53d1d89e1c0fc7f5a32520"`);
        await queryRunner.query(`ALTER TABLE "promedio_periodo" DROP CONSTRAINT "FK_c3f62a6aba1c6a8466f35a89ff2"`);
        await queryRunner.query(`ALTER TABLE "promedio_periodo" DROP CONSTRAINT "FK_f06c421ba51cb55d57d56c23e03"`);
        await queryRunner.query(`ALTER TABLE "promedio_periodo" DROP CONSTRAINT "FK_8da8000ef0d76c72fab20b817aa"`);
        await queryRunner.query(`ALTER TABLE "promedio_trimestre" DROP CONSTRAINT "FK_b0dff7d0f98f1dbcd69709302c3"`);
        await queryRunner.query(`ALTER TABLE "promedio_trimestre" DROP CONSTRAINT "FK_e47cd9f104abba623ebb012f9a3"`);
        await queryRunner.query(`ALTER TABLE "promedio_trimestre" DROP CONSTRAINT "FK_bf47d4453423f18490cc7d6292a"`);
        await queryRunner.query(`ALTER TABLE "materias_curso" DROP CONSTRAINT "FK_bf8b5544d0448fbf0a8bb31628d"`);
        await queryRunner.query(`ALTER TABLE "materias_curso" DROP CONSTRAINT "FK_feff830e9610edbe55a9b6b3b32"`);
        await queryRunner.query(`ALTER TABLE "materias_curso" DROP CONSTRAINT "FK_84877e0a4ff0be4b67f1b16274c"`);
        await queryRunner.query(`ALTER TABLE "materias_curso" DROP CONSTRAINT "FK_c8f507cef7e765cc533a23198c7"`);
        await queryRunner.query(`ALTER TABLE "matriculas" DROP CONSTRAINT "FK_bd71f878d96006eeead7b7f5d80"`);
        await queryRunner.query(`ALTER TABLE "matriculas" DROP CONSTRAINT "FK_de4dc94e001d9d72471c4937c50"`);
        await queryRunner.query(`ALTER TABLE "matriculas" DROP CONSTRAINT "FK_12610cedecedccac6383361b8c0"`);
        await queryRunner.query(`ALTER TABLE "cursos" DROP CONSTRAINT "FK_8c39b6011fb5a0da2a7c8f1b5dd"`);
        await queryRunner.query(`ALTER TABLE "cursos" DROP CONSTRAINT "FK_2462e222e2e234709464df31bc6"`);
        await queryRunner.query(`ALTER TABLE "trimestres" DROP CONSTRAINT "FK_f78557fe53353dc34626b3a2ea5"`);
        await queryRunner.query(`ALTER TABLE "tipos_evaluacion" DROP CONSTRAINT "FK_36bab68eb442843210f999f0bff"`);
        await queryRunner.query(`ALTER TABLE "docentes" DROP CONSTRAINT "FK_9fd711f473f0f2bf472de152688"`);
        await queryRunner.query(`DROP TABLE "calificacion_componente_cualitativo"`);
        await queryRunner.query(`DROP TYPE "public"."calificacion_componente_cualitativo_calificacion_enum"`);
        await queryRunner.query(`DROP TABLE "calificacion_examen"`);
        await queryRunner.query(`DROP TABLE "calificacion_proyecto"`);
        await queryRunner.query(`DROP TABLE "calificacion_insumo"`);
        await queryRunner.query(`DROP TABLE "recuperacion_insumo"`);
        await queryRunner.query(`DROP TABLE "insumos"`);
        await queryRunner.query(`DROP TYPE "public"."insumos_estado_enum"`);
        await queryRunner.query(`DROP TABLE "promedio_periodo"`);
        await queryRunner.query(`DROP TYPE "public"."promedio_periodo_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."promedio_periodo_cualitativa_final_enum"`);
        await queryRunner.query(`DROP TYPE "public"."promedio_periodo_cualitativa_anual_enum"`);
        await queryRunner.query(`DROP TABLE "promedio_trimestre"`);
        await queryRunner.query(`DROP TYPE "public"."promedio_trimestre_cualitativa_enum"`);
        await queryRunner.query(`DROP TABLE "materias_curso"`);
        await queryRunner.query(`DROP TYPE "public"."materias_curso_estado_enum"`);
        await queryRunner.query(`DROP TABLE "materias"`);
        await queryRunner.query(`DROP TYPE "public"."materias_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."materias_tipocalificacion_enum"`);
        await queryRunner.query(`DROP TYPE "public"."materias_niveleducativo_enum"`);
        await queryRunner.query(`DROP TABLE "estudiantes"`);
        await queryRunner.query(`DROP TYPE "public"."estudiantes_estado_enum"`);
        await queryRunner.query(`DROP TABLE "matriculas"`);
        await queryRunner.query(`DROP TYPE "public"."matriculas_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."matriculas_origen_enum"`);
        await queryRunner.query(`DROP TABLE "cursos"`);
        await queryRunner.query(`DROP TYPE "public"."cursos_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."cursos_especialidad_enum"`);
        await queryRunner.query(`DROP TYPE "public"."cursos_nivel_enum"`);
        await queryRunner.query(`DROP TABLE "trimestres"`);
        await queryRunner.query(`DROP TYPE "public"."trimestres_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."trimestres_nombre_enum"`);
        await queryRunner.query(`DROP TABLE "periodos_lectivos"`);
        await queryRunner.query(`DROP TYPE "public"."periodos_lectivos_estado_enum"`);
        await queryRunner.query(`DROP TABLE "tipos_evaluacion"`);
        await queryRunner.query(`DROP TYPE "public"."tipos_evaluacion_nombre_enum"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TYPE "public"."usuarios_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."usuarios_rol_enum"`);
        await queryRunner.query(`DROP TABLE "docentes"`);
        await queryRunner.query(`DROP TYPE "public"."docentes_nivelasignado_enum"`);
    }

}
